name: CI Validation

on:
  pull_request:
    branches:
      - dev

permissions:
  id-token: write
  contents: write
  packages: write
  actions: read
  security-events: write
  pull-requests: write
  
jobs:
  ci:    
    uses: Dhana008/java-platform/.github/workflows/platform-ci.yml@develop
    with:
      java-version: "17"
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      
  agent-check:
    uses: Dhana008/java-platform/.github/workflows/post-architect.yml@develop
    secrets: inherit
