name: CI Validation

on:
  pull_request:
    branches:
      - main


permissions:
  id-token: write
  contents: write
  packages: write
  actions: read
  security-events: write
  pull-requests: write
  
jobs:
  ci:
    uses: Rajkumar06706/java-github/blob/main/.github/workflows/platform-ci.yml@main
    with:
      java-version: "17"
    secrets:
      GITOPS_TOKEN: ${{ secrets.GITOPS_TOKEN }}
      
  agent-check:
    uses: Rajkumar06706/java-github/.github/workflows/post-architect.yml@main
    secrets: inherit
